[general]
import = [
  "~/.config/alacritty/alacritty.toml"
]

[colors.primary]
background = "#0d1117"
foreground = "#e6edf3"

[font]
size = 12

[font.normal]
family = "FantasqueSansMNerdFont"

[window.dimensions]
columns = 100
lines = 20
