use_nerdfont = true
notify = true
hide_display_names = true
library_tabs = ["tracks", "albums", "artists", "playlists"]

[keybindings]
"Shift+q" = "queue"
"Space" = "playpause"

[theme]
background = "#0d1117"
primary = "#e6edf3"
secondary = "#e6edf3"
title = "#58a6ff"
playing = "#0d1117"
playing_selected = "#58a6ff"
playing_bg = "#58a6ff"
highlight = "#58a6ff"
highlight_bg = "#484f58"
error = "#0d1117"
error_bg = "#ff7b72"
statusbar = "#4988d1"
statusbar_progress = "#58a6ff"
statusbar_bg = "#1c2f45"
cmdline = "#e6edf3"
cmdline_bg = "#0d1117"
search_match = "#f0883e"
