" Environment
set nocompatible
language en_US.UTF-8

" General
set background=dark
syntax enable
filetype plugin indent on
set encoding=utf-8
set autowrite
set autoread
set history=1000
set nospell
set hidden
set nobackup
set directory=/var/tmp,/tmp

" Vim UI
set showmode
set cursorline
set ruler
set showcmd
set laststatus=2
set backspace=indent,eol,start
set number
set showmatch
set incsearch
set hlsearch
set ignorecase
set smartcase
set wildmenu
set wildmode=list:longest,full
set whichwrap=b,s,<,>
set scrolloff=1
set foldenable
set list
set listchars=tab:▸\ ,trail:▫

" Formatting
set nowrap
set autoindent
set smartindent
set smarttab
set expandtab
set nojoinspaces
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Vim Theme
colorscheme habamax
