icons_format = "{icon}"

[theme]
theme = "native"
[theme.overrides]
info_bg = "#0f096a"
warning_bg = "#292199"
critical_bg = "#4039aa"

[icons]
icons = "awesome6"

[[block]]
block = "custom"
format = " \uf2d0 $text "
command = "~/.config/swaybar/scripts/window.sh"
interval = "once"
persistent = true
hide_when_empty = true

[[block]]
block = "music"
format = "{ $icon $combo.str(max_w:99) |}"
player = "ncspot"

[[block]]
block = "scratchpad"
format = "{ $count.eng(range:1..) $icon |}"

[[block]]
block = "cpu"
format = " $utilization $icon "
format_alt = " $frequency $icon "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
[[block.click]]
button = "middle"
cmd = "foot -a htop-cpu -T htop-cpu -W 160x40 htop"
[block.icons_overrides]
cpu = [ "\uf2db", "\uf2db", "\uf2db" ]

[[block]]
block = "disk_space"
format = " $percentage $icon "
format_alt = " $available / $total $icon "
path = "/"
info_type = "used"
warning = 50
alert = 75
[[block.click]]
button = "middle"
cmd = "foot -a btop-mem-disk -T btop-mem-disk -W 160x40 btop -p 6"

[[block]]
block = "memory"
format = " $mem_total_used_percents.eng(w:2) $icon "
format_alt = " $mem_avail / $mem_total $icon "
warning_mem = 60
critical_mem = 90
[block.icons_overrides]
memory_mem = "\uf538"
[[block.click]]
button = "middle"
cmd = "foot -a btop-mem-disk -T btop-mem-disk -W 160x40 btop -p 6"

[[block]]
block = "temperature"
format = " $max $icon "
format_alt = " $min min / $max max / $average avg $icon "
chip = "coretemp-isa-0000"
idle = 60
info = 70
warning = 80
[[block.click]]
button = "middle"
cmd = "foot -a btop-cpu -T btop-cpu -W 160x40 btop -p 5"

[[block]]
block = "sound"
format =" $volume.eng(w:2) $icon "
show_volume_when_muted = true
[[block.click]]
button = "right"
[[block.click]]
button = "wheel_up"
[[block.click]]
button = "wheel_down"

[[block]]
block = "net"
format = " $signal_strength $icon "
format_alt = " $device $ssid / $ip $icon "
device = "^wlan0$"
[block.icons_overrides]
net_wireless = "\uf012"
[[block.click]]
button = "middle"
cmd = "foot -a btop-net -T btop-net -W 160x40 btop -p 7"

# [[block]]
# block = "speedtest"
# format = " $speed_down.eng(w:4,u:B) / $speed_up.eng(w:4,u:B) "
# interval = 1800

# [[block]]
# block = "external_ip"
# format = " $ip $city ($country_code) "
# interval = 1800
# with_network_manager = false

[[block]]
block = "battery"
format = " $percentage $icon "
full_format = " $percentage $icon "
info = 90
warning = 40
critical = 10

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %e %b %k:%M:%S') "
[[block.click]]
button = "left"
[[block.click]]
button = "right"
[[block.click]]
button = "middle"
cmd = "foot -a peaclock -T peaclock peaclock --config-dir ~/.config/peaclock"

[[block]]
block = "tea_timer"
format = " $icon {$minutes:$seconds|} "
done_cmd = "dunstify 'Timer' 'Timer Finished'"
[[block.click]]
button = "wheel_up"
[[block.click]]
button = "wheel_down"
[block.icons_overrides]
tea = "\uf017"

[[block]]
block = "notify"
format = " $icon   "
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
cmd = "dunstctl close-all"
[block.icons_overrides]
bell = "\uf0c9"
bell-slash = "\uf0c9"
