#!/bin/bash
#
# https://codeberg.org/river/river/src/tag/v0.3.11/example/init
#

# Super+Return to start foot
riverctl map normal Super Return spawn foot

# Super+D to start fuzzel
riverctl map normal Super D spawn "${HOME}/.config/fuzzel/scripts/apps.sh list | fuzzel -l 13 -d --with-nth=1 --accept-nth=2 | ${HOME}/.config/fuzzel/scripts/apps.sh"

# Super+P to show clipboard history
riverctl map normal Super P spawn 'cliphist list | fuzzel -d -p "clipboard " --with-nth=2 | cliphist decode | wl-copy'

# Super+I to start firefox
riverctl map normal Super I spawn /usr/lib/firefox/firefox

# Super+E to start neovim
riverctl map normal Super V spawn 'foot -c ~/.config/foot/foot_github.ini -a neovim -e nvim'

# Super+X to lock screen
riverctl map normal Super X spawn swaylock

# Super+B to close waybar
riverctl map normal Super B spawn 'killall -SIGINT waybar'

# Super+Shift+B to start waybar
riverctl map normal Super+Shift B spawn waybar

# Super+N to close the latest notification
riverctl map normal Super N spawn 'dunstctl close'

# Super+Shift+N to close all notifications
riverctl map normal Super+Shift N spawn 'dunstctl close-all'

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Alt+{Up,Right,Down,Left} to focus the closest view in any direction
riverctl map normal Super+Alt Up focus-view up
riverctl map normal Super+Alt Right focus-view right
riverctl map normal Super+Alt Down focus-view down
riverctl map normal Super+Alt Left focus-view left

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Shift+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 4); do
  tags=$((1 << (i - 1)))

  # Super+[1-4] to focus tag [0-3]
  riverctl map normal Super "${i}" set-focused-tags $tags

  # Super+Shift+[1-4] to tag focused view with tag [0-3]
  riverctl map normal Super+Shift "${i}" set-view-tags $tags

  # Super+Control+[1-4] to toggle focus of tag [0-3]
  riverctl map normal Super+Control "${i}" toggle-focused-tags $tags

  # Super+Shift+Control+[1-4] to toggle tag [0-3] of focused view
  riverctl map normal Super+Shift+Control "${i}" toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

# Control pipewire audio volume with wpctl
riverctl map normal None XF86AudioMute spawn wireplumber-mute-toggle
riverctl map normal None XF86AudioLowerVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
riverctl map normal None XF86AudioRaiseVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
riverctl map normal Super F1 spawn wireplumber-mute-toggle
riverctl map normal Super F2 spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
riverctl map normal Super F3 spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'

# Control media players with playerctl
riverctl map normal None XF86AudioPlay spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPrev spawn 'playerctl previous'
riverctl map normal None XF86AudioNext spawn 'playerctl next'
riverctl map normal Super F4 spawn 'playerctl play-pause'
riverctl map normal Super F5 spawn 'playerctl previous'
riverctl map normal Super F6 spawn 'playerctl next'

# Control screen brightness with brightnessctl
riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
riverctl map normal None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
riverctl map normal Super F7 spawn 'brightnessctl set 5%-'
riverctl map normal Super F8 spawn 'brightnessctl set +5%'

# Make screenshots and pick colors with grim
riverctl map normal None Print spawn 'grimshot --notify save screen'
riverctl map normal Control Print spawn 'grimpicker --copy --notify'
riverctl map normal Shift Print spawn 'grimshot --notify save area'
riverctl map normal Control+Shift Print spawn 'grimshot --notify copy area'

# --------------------------

# Set border color
riverctl border-width 2
riverctl border-color-focused 0x2c3952
riverctl border-color-unfocused 0x09142b

# Set keyboard layout
riverctl keyboard-layout es

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Set cursor focus mode
riverctl focus-follows-cursor normal

# Make all views with these app ids start floating
riverctl rule-add -app-id 'firefox' -title 'Library' float
riverctl rule-add -app-id 'firefox' -title 'About*' float
riverctl rule-add -app-id 'qalc' float
riverctl rule-add -app-id 'nnn' float
riverctl rule-add -app-id 'qemu' float
riverctl rule-add -app-id 'dosbox' float
riverctl rule-add -app-id 'org.pulseaudio.pavucontrol' float

# Configure monitors
riverctl spawn 'wlr-randr --output HDMI-A-1 --mode 2560x1440@74.968002Hz --pos 0,0'
riverctl spawn 'wlr-randr --output eDP-1 --mode 1920x1080@60.000000Hz --pos 2560,0'

# Set background image
riverctl spawn 'swaybg -m stretch -i ~/Pictures/Wallpapers/macOS/001-macos-wallpaper-10-14-Night.jpg'

# Lock screen timeout
riverctl spawn 'swayidle -w timeout 600 swaylock'

### Start wayland bar
riverctl spawn waybar

### Start notification service
riverctl spawn dunst

### Start clipboard history service
riverctl spawn 'wl-paste --watch cliphist store'

### Reconfigure xdg-desktop-portal service
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
systemctl --user restart xdg-desktop-portal

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
