export ZSH=$HOME/.oh-my-zsh

if [[ "${TERM}" =~ "256color" ]]; then
  ZSH_THEME="hyperzsh"
else
  ZSH_THEME="basic"
fi

zstyle ':omz:update' mode disabled

plugins=(
  git
  thefuck
  fzf
  lsd
  fp
  pe
  z
  tmux
)

source $ZSH/oh-my-zsh.sh

export EDITOR="nvim"
export GPG_TTY="$(tty)"
export ZSH_THEME_TERM_TITLE_IDLE="%~"
export ZSH_TMUX_UNICODE="true"

alias v='nvim'
alias vc='~/.config/nvim/scripts/nvim-cleanup.lua'
alias t='tmux'
alias root='sudo su -'
alias n='nnn -deHoQTv'
alias sp='ncspot'
alias rbt='sudo systemctl reboot'
alias off='sudo systemctl poweroff'
alias sw='sway > /tmp/sway.log 2>&1'
alias lw='labwc > /tmp/labwc.log 2>&1'

if [[ -f ~/.zshrc.local ]]; then
  . ~/.zshrc.local
fi
