export ZSH="$HOME/.oh-my-zsh"
export ZSHZ_DATA="$HOME/.zshz"

if [[ "${TERM}" =~ "256color" ]]; then
  ZSH_THEME="hyperzsh"
else
  ZSH_THEME="console"
fi

zstyle ':omz:update' mode disabled

plugins=(
  git
  fzf
  bat
  fp
  lsd
  pe
  z
  dla
)

source $ZSH/oh-my-zsh.sh

export EDITOR="nvim"
export PAGER="less"
export GPG_TTY="$(tty)"
export ZSH_THEME_TERM_TAB_TITLE_IDLE="zsh (%~)"
export ZSH_THEME_TERM_TITLE_IDLE=$ZSH_THEME_TERM_TAB_TITLE_IDLE

alias v='nvim'
alias t='tmux new-session -A -s DEV'
alias root='sudo su -'
alias n='NNN_OPENER=nuke GUI=1 nnn -cdQTv'
alias sp='ncspot'
alias lg='lazygit'
alias ff='fastfetch'
alias rbt='sudo systemctl reboot'
alias off='sudo systemctl poweroff'
alias wm='river > /tmp/river.log 2>&1'

if [[ -f ~/.zshrc.local ]]; then
  . ~/.zshrc.local
fi
